version: "3.8"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bR5,*RRvjv6X!TY
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  backend:
    image: karanjoshi09/yatramitra-backend:latest
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:bR5,*RRvjv6X!TY@db:5432/postgres
      - JWT_SECRET=143f7f0ea3572f5d5cbea7fce653b4d8de241ae141390912e1aae798a60b4aed59d0f84f2c49986a166721da458ca694742b66146d2b74f49e0fdca8a5fa0d48
    restart: always
    depends_on:
      - db

  frontend:
    image: karanjoshi09/yatramitra-frontend:latest
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend

volumes:
  pgdata:
